Repository nsftx/chameleon-bundle-material, pull requests merged in 2018-09, with the labels that each got.

#73 Fix CTable columns when data is mapped chmjs/chameleon-vuetify#45
  src/components/CTable/CTable.js
Labels: bug

#78 Add http prefix if one is not present
  src/components/CRichText/CRichText.js
Labels: enhancement

#80 Remove multiline
  package-lock.json
  package.json
  src/components/CHtml/CHtml.js
  src/components/CHtml/index.meta.js
  src/components/CSelectList/CSelectList.js
  src/components/CVideoStream/index.meta.js
Labels: bug

#77 Feature/height handling
  src/components/CPage/CPage.js
  src/components/CPage/index.meta.js
Labels: enhancement

#81 Upgrade rating component
  dev/data/form.json
  dev/data/page.json
  src/components/CRating/CRating.js
  src/components/CRating/index.meta.js
  src/components/CText/CText.js
  src/style/components/_rating.styl
Labels: enhancement

#83 Bugfix/video
  build/manifest.json
  src/components/CVideo/CVideo.js
  src/components/CVideo/index.meta.js
Labels: bug

#76 Don't allow inputs in container items #75
  src/components/CAccordionItem/index.meta.js
  src/components/CFlexgridItem/index.meta.js
  src/components/CTabItem/index.meta.js
Labels: bug

#91 Create Actions elements group #90
  src/components/CButton/index.meta.js
  src/components/CSwitch/index.meta.js
  src/index.meta.js
Labels: enhancement

#89 Bugfix/double source load
  dev/data/page.json
  dev/data/table.json
  src/components/CCheckList/CCheckList.js
  src/components/CGallery/CGallery.js
  src/components/CList/CList.js
  src/components/CMenu/CMenu.js
  src/components/CRadioList/CRadioList.js
  src/components/CSelect/CSelect.js
  src/components/CTable/CTable.js
Labels: bug

#97 Added button icon position and padding
  dev/data/vlist.json
  package-lock.json
  package.json
  src/components/CButton/CButton.js
  src/components/CButton/index.meta.js
Labels: enhancement

#100 Add html icon to make it visable, enable color and theme
  dev/data/vlist.json
  src/components/CHtml/CHtml.js
  src/components/CHtml/index.meta.js
  tests/unit/specs/__snapshots__/elements.spec.js.snap
Labels: bug, enhancement

#101 Feature/entity field name
  dev/data/accordion.json
  dev/data/page.json
  dev/data/vlist.json
  src/components/CCalculation/CCalculation.js
  src/components/CCalculation/index.meta.js
  src/components/CCheck/index.meta.js
  src/components/CCheckList/index.meta.js
  src/components/CDate/index.meta.js
  src/components/CDateRange/index.meta.js
  src/components/CForm/CForm.js
  src/components/CRadioList/index.meta.js
  src/components/CRating/index.meta.js
  src/components/CRichText/index.meta.js
  src/components/CSelect/index.meta.js
  src/components/CSelectList/index.meta.js
  src/components/CSlider/index.meta.js
  src/components/CTags/index.meta.js
  src/components/CText/CText.js
  src/components/CText/index.meta.js
  src/components/CTextArea/index.meta.js
  src/components/CVideo/CVideo.js
  src/components/CVideoStream/CVideoStream.js
  tests/unit/specs/__snapshots__/elements.spec.js.snap
  tests/unit/specs/elements.spec.js
Labels: bug, enhancement

#102 Make name option required for inputs #98
  src/components/CCalculation/index.meta.js
  src/components/CCheck/index.meta.js
  src/components/CCheckList/index.meta.js
  src/components/CDate/index.meta.js
  src/components/CDateRange/index.meta.js
  src/components/CRadioList/index.meta.js
  src/components/CRating/index.meta.js
  src/components/CRichText/index.meta.js
  src/components/CSelect/index.meta.js
  src/components/CSelectList/index.meta.js
  src/components/CSlider/index.meta.js
  src/components/CTags/index.meta.js
  src/components/CText/index.meta.js
  src/components/CTextArea/index.meta.js
Labels: enhancement

#105 Enable map component
  dev/data/map.json
  src/components/CMap/CMap.js
  src/components/CMap/index.meta.js
  src/components/index.meta.js
Labels: bug, enhancement

#106 Floating (Speed dial) buttons
  dev/data/vlist.json
  src/components/CButton/CButton.js
  src/components/CFloatingButton/CFloatingButton.js
  src/components/CFloatingButton/index.js
  src/components/CFloatingButton/index.meta.js
  src/components/CFloatingButtonItem/CFloatingButtonItem.js
  src/components/CFloatingButtonItem/index.js
  src/components/CFloatingButtonItem/index.meta.js
  src/components/Element/index.js
  src/components/index.js
  src/components/index.meta.js
  tests/unit/specs/__snapshots__/elements.spec.js.snap
Labels: enhancement

#109 Fix youtube overlay position
  src/components/CYoutube/CYoutube.js
Labels: bug

#110 Fix form action buttons selection
  src/components/CForm/CForm.js
Labels: bug
