Repository nsftx/chameleon-bundle-material, pull requests merged in 2018-11, with the labels that each got.

#126 Support alterneting rows fixes #120
  src/components/CTable/CTable.js
  src/components/CTable/index.meta.js
  src/index.meta.js
Labels: enhancement

#128 Add additional accordion options
  dev/data/page.json
  package-lock.json
  package.json
  src/components/CAccordion/CAccordion.js
  src/components/CAccordion/index.meta.js
  src/components/CAccordionItem/CAccordionItem.js
  src/components/CAccordionItem/index.meta.js
Labels: enhancement

#127 Feature/context options
  src/components/CText/CText.js
  src/components/CText/index.meta.js
  tests/unit/specs/__snapshots__/elements.spec.js.snap
Labels: enhancement, refactoring

#130 Remove page layout height
  dev/data/page.json
  package-lock.json
  package.json
  src/components/CPage/CPage.js
  src/components/CPage/index.meta.js
  tests/unit/specs/__snapshots__/elements.spec.js.snap
Labels: enhancement

#132 Add null value for table color
  src/components/CTable/index.meta.js
Labels: bug

#135 Fix typo
  src/components/CTable/CTable.js
  src/components/CTable/index.meta.js
Labels: enhancement

#137 Treeview
  dev/data/navigation.json
  dev/data/page.json
  dev/data/treeview.json
  package-lock.json
  package.json
  src/components/CTreeview/CTreeview.js
  src/components/CTreeview/index.js
  src/components/CTreeview/index.meta.js
  src/components/index.js
  src/components/index.meta.js
  src/style/components/_treeview.styl
  tests/unit/specs/__snapshots__/elements.spec.js.snap
Labels: Type:Enhancement

#141 List widget
  dev/data/list.json
  src/components/CFlexgrid/CFlexgrid.js
  src/components/CList/CList.js
  src/components/CList/index.meta.js
  src/style/components/_list.styl
  tests/unit/specs/__snapshots__/elements.spec.js.snap
Labels: Type:Enhancement
