Repository nsftx/chameleon-bundle-material, pull requests merged in 2019-11, with the labels that each got.

#270 Fix padding
  build/manifest.json
  src/style/components/_vlist.scss
Labels: Type:Bug

#272 Fix image height
  build/manifest.json
  src/components/CImage/CImage.js
  src/style/components/_image.scss
Labels: Type:Bug

#274 Added required and unique validation to layout name
  src/components/CLayout/index.meta.js
Labels: Type:Enhancement

#275 Refactoring/remove moment
  .eslintrc.js
  build/manifest.json
  package-lock.json
  package.json
  public/data/form.json
  public/data/page.json
  public/index.html
  src/components/CCalendar/CCalendar.js
  src/components/CDate/CDate.js
  src/components/CDate/index.meta.js
  src/components/CDateRange/CDateRange.js
  src/components/CDateRange/index.meta.js
  src/components/CPicker/CPicker.js
  tests/unit/setup.js
Labels: Type:Refactoring
