Repository nsftx/chameleon-bundle-material, pull requests merged in 2019-08, with the labels that each got.

#242 Filter Group
  package-lock.json
  package.json
  public/data/form.json
  src/components/CFilterGroup/CFilterGroup.js
  src/components/CFilterGroup/index.js
  src/components/CFilterGroup/index.meta.js
  src/components/CFlexgrid/index.meta.js
  src/components/CRating/CRating.js
  src/components/CSlider/CSlider.js
  src/components/CTextArea/CTextArea.js
  src/components/Element/index.js
  src/components/index.js
  src/components/index.meta.js
  src/style/components/_filter-group.styl
Labels: Type:Enhancement

#243 Change item value for page meta nsftx/chameleon-builder#72
  build/manifest.json
  src/components/CPage/index.meta.js
  src/components/Element/index.js
Labels: Type:Enhancement

#244 Import optimizations
  babel.config.js
  package-lock.json
  package.json
  src/validators/creditCardValidator.js
  src/validators/integerValidator.js
  src/validators/maxCountValidator.js
  src/validators/maxLengthValidator.js
  src/validators/minCountValidator.js
  src/validators/minLengthValidator.js
  src/validators/requiredValidator.js
  src/validators/urlValidator.js
  vue.config.js
Labels: Category:Optimization

#247 Lazy load tab item children nsftx/chameleon-bundle-charts#8
  build/manifest.json
  src/components/CTabItem/CTabItem.js
  src/components/CTabs/CTabs.js
Labels: Type:Bug

#248 Bugfix/table touchend
  build/manifest.json
  package-lock.json
  src/components/CTable/CTable.js
Labels: Type:Bug

#249 Red bull
  package-lock.json
  public/data/accordion.json
  public/data/hlist.json
  public/data/page.json
  public/data/vlist.json
  public/data/youtube.json
  src/components/CHlist/CHlist.js
  src/components/CHlist/index.meta.js
  src/components/CPanel/CPanel.js
  src/components/CPanel/index.meta.js
  src/components/CTable/CTable.js
  src/components/CTable/index.meta.js
  src/components/CVlist/CVlist.js
  src/components/CVlist/index.meta.js
  src/style/components/_hlist.styl
  src/style/components/_panel.styl
  src/style/components/_vlist.styl
Labels: Type:Enhancement

#250 OptionsNumberInput elements
  package-lock.json
  src/components/CAccordion/index.meta.js
  src/components/CCheckList/index.meta.js
  src/components/CFlexgrid/index.meta.js
  src/components/CFloatingButton/index.meta.js
  src/components/CList/index.meta.js
  src/components/CSlider/index.meta.js
  src/components/CTable/index.meta.js
  src/components/CTabs/index.meta.js
  src/components/CTextArea/index.meta.js
  src/components/CTextInput/index.meta.js
Labels: Type:Enhancement
