Repository nsftx/chameleon-bundle-material, pull requests merged in 2019-06, with the labels that each got.

#209 Input clear option #150
  src/components/CCalculation/index.meta.js
  src/components/CCalendar/index.meta.js
  src/components/CCheck/index.meta.js
  src/components/CCheckList/index.meta.js
  src/components/CDate/index.meta.js
  src/components/CDateRange/index.meta.js
  src/components/CList/index.meta.js
  src/components/CRadioList/index.meta.js
  src/components/CRating/index.meta.js
  src/components/CRichText/index.meta.js
  src/components/CSelect/index.meta.js
  src/components/CSelectList/index.meta.js
  src/components/CSlider/index.meta.js
  src/components/CTable/index.meta.js
  src/components/CTabs/index.meta.js
  src/components/CTags/index.meta.js
  src/components/CText/index.meta.js
  src/components/CTextInput/index.meta.js
  src/components/CVideoStream/index.meta.js
Labels: Type:Enhancement

#212 added new option: Show in menu to CPage element
  public/data/form.json
  public/data/navigation.json
  src/components/CPage/index.meta.js
Labels: Type:Enhancement

#215 added default value true to option showInMenu in CPage element
  build/manifest.json
  src/components/CPage/index.meta.js
Labels: Type:Enhancement

#214 pages from CMenu component were filtered by showInMenu property
  package-lock.json
  public/data/menu.json
  src/components/CMenu/CMenu.js
Labels: Type:Enhancement

#208 Remove start with page option #207
  build/manifest.json
  public/data/list.json
  public/data/page.json
  public/data/table.json
  src/components/CList/CList.js
  src/components/CList/index.meta.js
  src/components/CTable/CTable.js
  src/components/CTable/index.meta.js
Labels: Type:Enhancement

#216 add text value length check
  src/components/CText/CText.js
Labels: Type:Bug

#217 fix float number on slider #210
  src/components/CSlider/index.meta.js
  src/validators/maxValidator.js
  src/validators/minValidator.js
Labels: Type:Bug

#219 Feature/flex grid height
  build/manifest.json
  src/components/CFlexgrid/CFlexgrid.js
  src/components/CFlexgrid/index.meta.js
  src/components/CFlexgridItem/CFlexgridItem.js
  src/components/CFlexgridItem/index.meta.js
Labels: Type:Enhancement

#220 Switch deploy script to use basic auth
  build/deploy.js
Labels: Type:Enhancement

#221 Bug fix/input list
  src/components/CText/CText.js
  src/style/components/_text.styl
Labels: Type:Bug, Type:Enhancement

#222 Feature/remove auto submit from c form
  build/manifest.json
  src/components/CForm/CForm.js
  src/components/CForm/index.meta.js
Labels: Type:Enhancement

#225 Fail build if lint errors are present
  src/components/CForm/index.meta.js
  vue.config.js
Labels: Type:Bug

#224 Bug/close stream
  src/components/CVideo/CVideo.js
  src/components/CVideoStream/CVideoStream.js
Labels: Type:Bug

#223 fix text element #nsftx/chameleon-builder/issues/478/
  build/manifest.json
  src/components/CText/CText.js
  src/style/components/_text.styl
Labels: Type:Bug, Type:Enhancement

#226 Bug fix/flex grid wrap
  build/manifest.json
  src/components/CFlexgrid/CFlexgrid.js
Labels: Category:QA, Type:Bug

#227 added property to meta data for ear validation #443
  build/manifest.json
  src/components/CTable/index.meta.js
Labels: Type:Enhancement
