Repository nsftx/chameleon-bundle-material, pull requests merged in 2019-05, with the labels that each got.

#199 Page layout component
  package-lock.json
  package.json
  src/components/CLayout/CLayout.js
  src/components/CLayout/index.js
  src/components/CLayout/index.meta.js
  src/components/CMenu/CMenu.js
  src/components/CMenu/index.meta.js
  src/components/CPage/CPage.js
  src/components/CPage/index.meta.js
  src/components/index.js
  src/components/index.meta.js
  src/index.js
  src/style/components/_layout.styl
Labels: Type:Enhancement

#200 Render just page without layout
  src/components/CPage/CPage.js
Labels: Type:Bug

#201 Fix menu from href to router click
  src/components/CMenu/CMenu.js
Labels: Type:Bug, Type:Enhancement

#204 Bugfix/node image
  .circleci/config.yml
Labels: Type:Bug

#205 add repeater shadow option #203
  package-lock.json
  package.json
  src/components/CRepeater/index.meta.js
Labels: Type:Enhancement
