Repository nsftx/chameleon-bundle-material, pull requests merged in 2019-03, with the labels that each got.

#176 Update repeater element (enabled element nesting)
  src/components/CRepeater/CRepeater.js
Labels: Type:Enhancement

#178 Removed double mixin (theme) definition
  src/components/CGallery/index.meta.js
  src/components/CHtml/index.meta.js
  src/components/CPage/CPage.js
  src/components/CRepeater/index.meta.js
  src/components/CRichText/index.meta.js
  src/components/CTextArea/index.meta.js
  src/components/CTextInput/CTextInput.js
  src/components/CTextInput/index.meta.js
  src/components/CTreeview/index.meta.js
  src/components/CVideo/index.meta.js
  src/components/CVideoStream/index.meta.js
  src/components/CYoutube/index.meta.js
  src/components/Element/index.js
  src/mixins/index.js
  src/mixins/themeable.js
Labels: Type:Refactoring

#180 Bump Chameleon SDK version
  build/deploy.js
  build/manifest.json
  package-lock.json
  package.json
Labels: Type:Enhancement

#181 Check if string empty
  src/components/CText/CText.js
Labels: Type:Bug

#186 Bundle script fix
  build/manifest.json
  package-lock.json
  package.json
  public/data/page.json
  src/components/CPage/CPage.js
  src/components/CPage/index.meta.js
  src/main.js
  tests/unit/spec/__snapshots__/elements.spec.js.snap
  vue.config.js
Labels: Type:Bug

#187 Fix Chameleon Vuetify playground
  .gitignore
  .netlify/state.json
  netlify.toml
  package.json
  vue.config.js
Labels: Type:Bug

#188 Remove local Netlify site config
  .netlify/state.json
  package.json
Labels: Type:Enhancement
